apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-components
  namespace: github-runner
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: git@github.com:org-demo-6za/gitops.git
    path: components/github-runner
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: github-runner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2
